language: node_js

# 4.3.2 is what AWS Lambda currently uses
node_js:
  - "6"
  - "4.3.2"

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
